version: 1.0.{build}

before_build:
  - git clone --depth 1 https://github.com/mupen64plus/mupen64plus-core.git ..\mupen64plus-core

build_script:
  - msbuild projects\msvc\mupen64plus-rsp-hle.vcxproj /p:Configuration=Release;Platform=x64
  - msbuild projects\msvc\mupen64plus-rsp-hle.vcxproj /p:Configuration=Release;Platform=Win32

after_build:
  - ps: $env:rev = git describe --tags
  - 7z a -t7z "build\mupen64plus-rsp-hle_v%rev%_x64.7z" ".\projects\msvc\x64\Release\*.dll"
  - 7z a -t7z "build\mupen64plus-rsp-hle_v%rev%_x86.7z" ".\projects\msvc\Win32\Release\*.dll"

artifacts:
  - path: build\*.7z
    name: RSP HLE
